# Generated by Django 4.1.2 on 2022-10-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('sold', models.BooleanField(default=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('RC', 'Records'), ('CL', 'Clothing'), ('PS', 'Posters'), ('Misc', 'Miscellaneous')], max_length=5)),
            ],
        ),
    ]
